### ISSUE TITLE
节点名称转义符好像没有替代

### ISSUE THREAD

**Issue by 365cent** [yb/uptime-status#10]
我看到我的页面上的`&#091;`和`&#093;`没有换成"["和"]"
`return encodeURIComponent(e).replace(/%40/gi, "@").replace(/%3A/gi, ":").replace(/%24/g, "$").replace(/%2C/gi, ",").replace(/%20/g, "+").replace(/%5B/gi, "[").replace(/%5D/gi, "]")`
我找到了前面替代url的部分，但是不知道哪个值是nodename
麻烦大佬改一下

**Comment by yb** [comment]
在刚刚更新的 v1.4.0 中已经完善了这个问题，谢谢
