### ISSUE TITLE
不支持显示特殊符号

### ISSUE THREAD

**Issue by TomsProject** [yb/uptime-status#11]
你好，你这个项目真的很棒
但是似乎没有对特殊符号进行处理
这是显示出来的效果
![image](https://user-images.githubusercontent.com/44722363/88914267-f4aa0f80-d294-11ea-849e-0478b9d9fea2.png)
这是在UptimeRobot控制台显示的效果
![image](https://user-images.githubusercontent.com/44722363/88913809-3c7c6700-d294-11ea-96b7-b9136094a2e4.png)
似乎官方的API返回的就是这样子的，是不是需要特殊处理？
`{"stat":"ok","pagination":{"offset":0,"limit":50,"total":1},"monitors":[{"id":785645632,"friendly_name":"新浪微博&#40;接口&#41;",`

**Comment by TomsProject** [comment]
貌似把 uptimerobot.js 的 monitor.friendly_name 内容替换一下就可以了（Chrome 84 可以，其它浏览器没试）
```javascript
    let name = monitor.friendly_name.replace(/&#39;/gi, "'");
    name = name.replace(/&#40;/gi, "(");
    name = name.replace(/&#41;/gi, ")");
    name = name.replace(/&#061;/gi, "=");
    name = name.replace(/&#091;/gi, "[");
    name = name.replace(/&#093;/gi, "]");
    name = name.replace(/&quot;/gi, '"');
    name = name.replace(/&lt;/gi, "<");
    name = name.replace(/&gt;/gi, ">");

    apps.push({
      id: monitor.id,
      name: name,
      url: monitor.url,
      status: status,
      average: average,
      daily: daily,
      total: total,
    });
```
// 烂代码，大佬勿喷

**Comment by renbaoshuo** [comment]
我觉得封装成函数更好一些

```node
function convert(str){ 
  str = str.replace(/(\\u)(\w{1,4})/gi, function($0){ 
      return (String.fromCharCode(parseInt((escape($0).replace(/(%5Cu)(\w{1,4})/g,"$2")),16))); 
  }).replace(/(&#x)(\w{1,4});/gi, function($0){ 
      return String.fromCharCode(parseInt(escape($0).replace(/(%26%23x)(\w{1,4})(%3B)/g,"$2"),16)); 
  }).replace(/(&#)(\d{1,6});/gi, function($0){ 
      return String.fromCharCode(parseInt(escape($0).replace(/(%26%23)(\d{1,6})(%3B)/g,"$2"))); 
  }); 
  return str; 
}
```

方便调用

**Comment by yb** [comment]
HTML 实体符号挺多的，靠 replace 无法从根本解决问题，在最新的 v1.4.0 更新中引入了 htmr 进行转义，已解决这个问题；
谢谢二位提出的 issue！

**Comment by renbaoshuo** [comment]
> HTML 实体符号挺多的，靠 replace 无法从根本解决问题，在最新的 v1.4.0 更新中引入了 htmr 进行转义，已解决这个问题；
> 谢谢二位提出的 issue！

@yb  另外，我稍改了一下页面样式，适配了我所用的主题，页面链接：https://renbaoshuo.github.io/status/ 页面下方已经注明版权，请问可以吗？

![a1I7iq.png](https://s1.ax1x.com/2020/08/01/a1I7iq.png)

**Comment by yb** [comment]
> @yb 另外，我稍改了一下页面样式，适配了我所用的主题，页面链接：https://renbaoshuo.github.io/status/ ，且页面下方已经注明版权，请问可以吗？

of course，欢迎使用
