### ISSUE TITLE
大佬 现在是失效了嘛

### ISSUE THREAD

**Issue by 957life** [yb/uptime-status#14]
我下载了release的压缩包，修改了config.js里面的ApiKeys，SiteName，SiteUrl  key用的是Read-Only只读key，打开index.html  一片空白 0.0

**Comment by 957life** [comment]
<title>Uptime Status</title>
  <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" type="image/x-icon" />
  <script src="%PUBLIC_URL%/config.js"></script>

是这个PUBLIC_URL的问题嘛，我看了下代码没有地方声明了这个变量，还是我哪一步错了呀，求大佬指教

**Comment by yb** [comment]
release 的 `index.html` 中是没有 `<script src="%PUBLIC_URL%/config.js">` 这个语句的，你下载的是 source code 压缩包吧，应该下载 **uptime-status.zip** 这个

**Comment by YQHP-YuKi** [comment]
大佬，我是在服务器里面安装的uptime-status.zip，也改了API，但是为什么我的博客域名+服务器文件还是打不开，是怎么打开

**Comment by YQHP-YuKi** [comment]
就是404

**Comment by yb** [comment]
不是很明白什么意思，听起来像是服务器配置的问题。
如果 404 页面是 http server 响应的（比如 apache / nginx），那应该检查一下服务器是否配置了你安装的目录。或者在你说的目录中放入其它的 `index.html` 看看是否能正常访问。
