### ISSUE TITLE
PC浏览器访问不显示数据

### ISSUE THREAD

**Issue by kaoruray** [yb/uptime-status#17]
不论是自己搭建的还是演示站，在PC上换了3个浏览器，页面能正常显示，但显示数据的部分一直转圈，用手机访问正常，这是哪的问题？

**Comment by censujiang** [comment]
我也遇到相同问题，但是手机访问也不正常

**Comment by a6513375** [comment]
跨域报错 应该是API的问题
"Access to XMLHttpRequest at 'https://api.uptimerobot.com/v2/getMonitors' from origin 'https://status.org.cn' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

**Comment by renfei** [comment]
我已经提交合并请求 #18 来临时解决这个问题，需要的朋友可以将 
```javascript
const Api = 'https://api.uptimerobot.com/v2/getMonitors';
```
改为
```javascript
const Api = 'https://uptimerobot.renfei.workers.dev/v2/getMonitors';
```
可以临时解决这个问题，想要根本解决的话，还需自己搭建反代服务。

**Comment by iiivii** [comment]
CF Workers反代代码：
```javascript
addEventListener("fetch", event => {
  let url = new URL(event.request.url);
  url.hostname = "api.uptimerobot.com"; 

  let request = new Request(url, event.request);
  event.respondWith(
    fetch(request, {
      headers: {
        'Referer': 'https://www.cloudflare.com/', 
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36' 
      }
    })
  );
});
```

**Comment by iiivii** [comment]
> 我已经提交合并请求 #18 来临时解决这个问题，需要的朋友可以将 `src/utils/uptimerobot.js`中
> 
> ```js
> const Api = 'https://api.uptimerobot.com/v2/getMonitors';
> ```
> 
> 改为
> 
> ```js
> const Api = 'https://uptimerobot-api.renfei.net/v2/getMonitors';
> ```
> 
> 可以临时解决这个问题，想要根本解决的话，还需自己搭建反代服务。

请问可以po一份CF的workers的反代源码吗？

**Comment by renfei** [comment]
> > 我已经提交合并请求 #18 来临时解决这个问题，需要的朋友可以将 `src/utils/uptimerobot.js`中
> > ```js
> > const Api = 'https://api.uptimerobot.com/v2/getMonitors';
> > ```
> > 
> > 
> > 改为
> > ```js
> > const Api = 'https://uptimerobot-api.renfei.net/v2/getMonitors';
> > ```
> > 
> > 
> > 可以临时解决这个问题，想要根本解决的话，还需自己搭建反代服务。
> 
> 请问可以po一份CF的workers的反代源码吗？

好的，由于是我临时解决这个问题，没有想太多，以下代码没有调优，只是我手写实现了功能，可以作为参考：
```javascript
async function handleRequest(request) {
  let apiUrl = request.url.replace("uptimerobot-api.renfei.net","api.uptimerobot.com")
  request = new Request(apiUrl, request)
  let response = await fetch(request)
  response = new Response(response.body, response)
  response.headers.set("Access-Control-Allow-Origin", "*")
  response.headers.set("Access-Control-Allow-Methods", "*")
  response.headers.set("Access-Control-Allow-Credentials", "true")
  response.headers.set("Access-Control-Allow-Headers", "Content-Type,Access-Token")
  response.headers.set("Access-Control-Expose-Headers", "*")
  return response
}

addEventListener("fetch", event => {
  const request = event.request
  event.respondWith(handleRequest(request))
})
```

**Comment by iiivii** [comment]
> > > 我已经提交合并请求 #18 来临时解决这个问题，需要的朋友可以将 `src/utils/uptimerobot.js`中
> > > ```js
> > > const Api = 'https://api.uptimerobot.com/v2/getMonitors';
> > > ```
> > > 
> > > 
> > > 改为
> > > ```js
> > > const Api = 'https://uptimerobot-api.renfei.net/v2/getMonitors';
> > > ```
> > > 
> > > 
> > > 可以临时解决这个问题，想要根本解决的话，还需自己搭建反代服务。
> > 
> > 
> > 请问可以po一份CF的workers的反代源码吗？
> 
> 好的，由于是我临时解决这个问题，没有想太多，以下代码没有调优，只是我手写实现了功能，可以作为参考：
> 
> ```js
> async function handleRequest(request) {
>   let apiUrl = request.url.replace("uptimerobot-api.renfei.net","api.uptimerobot.com")
>   request = new Request(apiUrl, request)
>   let response = await fetch(request)
>   response = new Response(response.body, response)
>   response.headers.set("Access-Control-Allow-Origin", "*")
>   response.headers.set("Access-Control-Allow-Methods", "*")
>   response.headers.set("Access-Control-Allow-Credentials", "true")
>   response.headers.set("Access-Control-Allow-Headers", "Content-Type,Access-Token")
>   response.headers.set("Access-Control-Expose-Headers", "*")
>   return response
> }
> 
> addEventListener("fetch", event => {
>   const request = event.request
>   event.respondWith(handleRequest(request))
> })
> ```

万分感谢！！！

**Comment by yb** [comment]
官网间歇性的 CORS 抽风，和 PC 浏览器无关，不是技术问题；
另外作为一个基于官网 API 的产品，我不会在代码中 hardcode 第三方接口，这对用户是不负责任的；
针对这个抽风问题，后续会增加自定义 API 域名配置，使不使用第三方接口应该交给用户选择；

**Comment by renfei** [comment]
> 官网间歇性的 CORS 抽风，和 PC 浏览器无关，不是技术问题；
> 另外作为一个基于官网 API 的产品，我不会在代码中 hardcode 第三方接口，这对用户是不负责任的；
> 针对这个抽风问题，后续会增加自定义 API 域名配置，使不使用第三方接口应该交给用户选择；

嗯，理解并支持您的严谨态度。

我当时也想了下会不会产生安全问题，但我看过官方文档以后，只读的key```read-only api_key```，并不能有任何操作权限，而且本来就是在页面中公开的，也可以通过网络请求里看到明文的key，而且数据都是一些监控数据，我认为没那么敏感，毕竟使用这个状态页的场景，就是公开让别人看的吧。

所以我就发出来了，作为目前没有很好的解决方案时的临时解决办法，让页面可以先展示出来，再慢慢研究解决办法。

![image](https://user-images.githubusercontent.com/6532952/108292512-24881880-71cf-11eb-8396-3ccc90067a8d.png)

**Comment by yb** [comment]
> > 官网间歇性的 CORS 抽风，和 PC 浏览器无关，不是技术问题；
> > 另外作为一个基于官网 API 的产品，我不会在代码中 hardcode 第三方接口，这对用户是不负责任的；
> > 针对这个抽风问题，后续会增加自定义 API 域名配置，使不使用第三方接口应该交给用户选择；
> 
> 嗯，理解并支持您的严谨态度。
> 
> 我当时也想了下会不会产生安全问题，但我看过官方文档以后，只读的key`read-only api_key`，并不能有任何操作权限，而且本来就是在页面中公开的，也可以通过网络请求里看到明文的key，而且数据都是一些监控数据，我认为没那么敏感，毕竟使用这个状态页的场景，就是公开让别人看的吧。
> 
> 所以我就发出来了，作为目前没有很好的解决方案时的临时解决办法，让页面可以先展示出来，再慢慢研究解决办法。
> 
> ![image](https://user-images.githubusercontent.com/6532952/108292512-24881880-71cf-11eb-8396-3ccc90067a8d.png)

不仅仅是数据隐私的问题，谁能保证第三方服务会一直 online 呢？
cf workers 免费版也是有请求次数限制的对不

**Comment by yb** [comment]
最新的 v.1.5.1 版本新增了 ApiDomain 配置，可自定义接口域名；
另外 README 中也增加了如何 Cloudflare Workers 搭建代码，欢迎更新；
