### ISSUE TITLE
调用公告信息？

### ISSUE THREAD

**Issue by dearroy** [yb/uptime-status#2]
留意到 UptimeRobot 的[官方 demo 页](https://status.uptimerobot.com/) 是有调用公告信息的，作者是否考虑增加？

**Comment by yb** [comment]
UptimeRobot 的控制台中没有找到发布公告的地方，API 也没有相应接口，你是否知道这公告在哪管理？

**Comment by dearroy** [comment]
@yb 这个功能是 Pro 版本才具有，参见[详情](https://blog.uptimerobot.com/new-feature-announcements-for-the-status-pages-pro-plan/)。

**Comment by yb** [comment]
@dearroy 没有 Pro 账号无法测试；另外看截图这个功能应该只在官方的 Public Status Page 中提供，不通过 API 提供。
