### ISSUE TITLE
日期显示问题

### ISSUE THREAD

**Issue by gd1214b** [yb/uptime-status#24]
![image](https://user-images.githubusercontent.com/37929478/118796658-6445c580-b8ce-11eb-81a2-c07e0e136c2d.png)
最新日期怎么永远是2021-03-21?

**Comment by yb** [comment]
从左到右是 今天 到 N 天之前，你配置的是 60 天，那里显示的便是 60 天前的日期。
你现在再看看是不是变成 2021-03-22 了？
