### ISSUE TITLE
我配置了页面却是白色的

### ISSUE THREAD

**Issue by Guyao146** [yb/uptime-status#26]
![image](https://user-images.githubusercontent.com/61780021/125466675-8a8ff1c1-6f60-4f37-adde-d801812ff29d.png)
你好，我刚刚配置了这个，但是却无法显示出来
这是我的网站  http://status.mcylyr.cn

**Comment by Guyao146** [comment]
填的是Main-Key

**Comment by 5icorgi** [comment]
> 填的是Main-Key

老哥不看注释的吗

**Comment by Guyao146** [comment]
> > 填的是Main-Key
> 
> 老哥不看注释的吗

忘记关掉issues了，不好意思，已经配置好了
