### ISSUE TITLE
建议给名字旁边的链接加个开关可以隐藏

### ISSUE THREAD

**Issue by benladen** [yb/uptime-status#3]
因为我有些监控的是IP，又不想暴露IP。开关可以在config里。
很不错的监控网页~~

**Comment by yb** [comment]
v1.3.0 的更新中已经增加了 ShowLink 配置；
另外要说明，这个配置只是隐藏了链接，并**不能**保护你的网址或IP，因为 UptimeRobot 的 API 输出就包含了这个属性，这不是我能控制的。
