### ISSUE TITLE
更新变慢了

### ISSUE THREAD

**Issue by pc655** [yb/uptime-status#36]
添加 或 删除 后,web要很久才能更新,,速度没有上一个版本快,
请问 能修改一下更新速度吗?

**Comment by iammeken** [comment]
更换默认接口地址解决 CORS 问题

**Comment by ipme** [comment]
@iammeken 现在好像用不了。一直在转圈。
请求网址: https://cors.status.org.cn/uptimerobot/v2/getMonitors    这个地址 也挂了。。
有什么办法没。。

**Comment by iammeken** [comment]
恢复默认的
