### ISSUE TITLE
[BUG]: getMonitor 返回 204 状态码

### ISSUE THREAD

**Issue by Pil0tXia** [yb/uptime-status#44]
![image](https://user-images.githubusercontent.com/41445332/213309235-d0272213-ef19-4a9e-a674-c1445b978b72.png)

问题站点：https://status.pil0txia.com

204应该是正常的，但是数据更新速度很慢，大概半小时到一小时一次，删掉存储桶里的文件、刷新CDN缓存、重新上传之后可以显示新的数据

期待回复，谢谢

**Comment by yb** [comment]
是因为我的代理接口开启了缓存，流量太大了，没办法
建议自己用 cloudflare 搭建一个代理接口
