### ISSUE TITLE
获取 不到具体状态了

### ISSUE THREAD

**Issue by dong-dong6** [yb/uptime-status#52]
![image](https://github.com/yb/uptime-status/assets/73739354/10a64002-fc87-4eff-aabf-7bf4d5f54539)
api正常，但是获取不到具体内容了
f12里
![image](https://github.com/yb/uptime-status/assets/73739354/deb40d45-df35-4fe6-bd0b-fd77915ed402)

**Comment by wangshengjj** [comment]
已经解决啦，可以自己使用Cloudflare的workers搭建一个反向代理api地址的网站，然后把main.ace24a8b.js文件中的api地址https://cors.status.org.cn/uptimerobot/v2/getMonitors 替换为你自己反向代理的地址域名即可解决，比如https://你的域名/v2/getMonitors

**Comment by KS-OTO** [comment]
能给一个cloudflare的worker的代码示例吗？😊😊😊
@wangshengjj

**Comment by dong-dong6** [comment]
我现在切换到这个项目了
https://github.com/louislam/uptime-kuma

**Comment by wangshengjj** [comment]
> 能给一个cloudflare的worker的代码示例吗？😊😊😊 @wangshengjj

当然可以
const TELEGRAPH_URL = 'https://api.uptimerobot.com';

addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

async function handleRequest(request) {
  const url = new URL(request.url);
  url.host = TELEGRAPH_URL.replace(/^https?:\/\//, '');

  const modifiedRequest = new Request(url.toString(), {
    headers: request.headers,
    method: request.method,
    body: request.body,
    redirect: 'follow'
  });

  const response = await fetch(modifiedRequest);
  const modifiedResponse = new Response(response.body, response);

  // 添加允许跨域访问的响应头
  modifiedResponse.headers.set('Access-Control-Allow-Origin', '*');

  return modifiedResponse;
}
