### ISSUE TITLE
api服务挂了

### ISSUE THREAD

**Issue by kilvn** [yb/uptime-status#56]
我自己的status调用返回502
![image](https://github.com/user-attachments/assets/56f9de7c-438c-42c3-a45d-e4bd64949df7)

https://status.org.cn/ 站请求api返回429
![image](https://github.com/user-attachments/assets/6716f256-1d75-48d1-bcc4-d084717d2fb7)

**Comment by kilvn** [comment]
看issue之前也有过这种问题，看起来是api服务不够稳定，是否考虑开源api代码，我们可以自己搭建

**Comment by yb** [comment]
api 就是一个反代到 uptimerebot 的接口而已，429 就是被 uptimerebot 判定为请求过多了
自己搭的话随便找个 cloudflare workers 反向代理的代码就可以实现，或者别的你习惯的开发语言都很容易做到
我部署接口的那台机器太久没登录，ssh 密钥不知搞哪去了…

**Comment by kilvn** [comment]
主要是不清楚你的api是自己对官方接口的数据处理，二次组织了数据结构，还是直接反带的，现在接口挂了没办法看数据结构了。。

刚才看了官方接口，直接反代恐怕不行，请求方式都不一样，能问下是反带的哪个接口吗

这是官方的
![image](https://github.com/user-attachments/assets/d856d0c4-2fc5-452d-9e42-9b7b26d97bb2)

这是你的api
![image](https://github.com/user-attachments/assets/02c2124d-540e-4f96-8dcd-85b97b7fbce2)


我有几台空置服务器，可以很轻易的做个反代

**Comment by kilvn** [comment]
已解决，找到文档了 https://uptimerobot.com/api/#getMonitorsWrap

**Comment by iougemini** [comment]
> 已解决，找到文档了 https://uptimerobot.com/api/#getMonitorsWrap

能讲下怎么反代的吗？

**Comment by kilvn** [comment]
> > 已解决，找到文档了 https://uptimerobot.com/api/#getMonitorsWrap
> 
> 
> 
> 能讲下怎么反代的吗？

主要是代理这个接口，当前项目唯一用到的接口
https://api.uptimerobot.com/v2/getMonitors

我把整个/v2路径都代理了，看下圈起来的就行
![image](https://github.com/user-attachments/assets/e517f912-2f68-4c88-917e-a2008fa4e656)

意思就是请求你nginx的/v2路径下任何url都转发流量到https://api.uptimerobot.com/v2官方

然后修改项目里面的api地址为
https://你的域名/v2/getMonitors

**Comment by iougemini** [comment]
> > > 已解决，找到文档了 https://uptimerobot.com/api/#getMonitorsWrap
> > 
> > 
> > 能讲下怎么反代的吗？
> 
> 主要是代理这个接口，当前项目唯一用到的接口 https://api.uptimerobot.com/v2/getMonitors
> 
> 我把整个/v2路径都代理了，看下圈起来的就行 ![image](https://private-user-images.githubusercontent.com/16423601/376662282-e517f912-2f68-4c88-917e-a2008fa4e656.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDQ3MTksIm5iZiI6MTcyOTAwNDQxOSwicGF0aCI6Ii8xNjQyMzYwMS8zNzY2NjIyODItZTUxN2Y5MTItMmY2OC00Yzg4LTkxN2UtYTIwMDhmYTRlNjU2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxNTAwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2FmNmFiNzY5YzY2NTM0M2M5ZTBlOTRiN2MwNzhjNTdmNmFmYTNmM2ZjNzU5ZmUxNWY2NTIwYWJiYWM1MjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UyKezEeg28tS5LidOgTO1qvZzaZkkIcaOrLLRMZgCEA)
> 
> 意思就是请求你nginx的/v2路径下任何url都转发流量到[https://api.uptimerobot.com/v2官方](https://api.uptimerobot.com/v2%E5%AE%98%E6%96%B9)
> 
> 然后修改项目里面的api地址为 [https://你的域名/v2/getMonitors](https://%E4%BD%A0%E7%9A%84%E5%9F%9F%E5%90%8D/v2/getMonitors)

非常感谢，按照这个方法搞了个workers搞定了。再次感谢

**Comment by yb** [comment]
> 主要是不清楚你的api是自己对官方接口的数据处理，二次组织了数据结构，还是直接反带的，现在接口挂了没办法看数据结构了。。
> 
> 刚才看了官方接口，直接反代恐怕不行，请求方式都不一样，能问下是反带的哪个接口吗

看了一下 nginx 的配置，并没有二次组织数据结构：

```
server {
  listen [::]:80;
  server_name cors.status.org.cn;
  location /uptimerobot/ {
    proxy_ssl_server_name on;
    proxy_pass https://api.uptimerobot.com/;
    proxy_hide_header Access-Control-Allow-Origin;
    proxy_cache uptimerobot;
    proxy_cache_methods POST;
    add_header Access-Control-Allow-Origin * always;
  }
  location / {
    return 301 https://status.org.cn;
  }
}
```

**Comment by kilvn** [comment]
> > 主要是不清楚你的api是自己对官方接口的数据处理，二次组织了数据结构，还是直接反带的，现在接口挂了没办法看数据结构了。。
> > 刚才看了官方接口，直接反代恐怕不行，请求方式都不一样，能问下是反带的哪个接口吗
> 
> 看了一下 nginx 的配置，并没有二次组织数据结构：
> 
> ```
> server {
>   listen [::]:80;
>   server_name cors.status.org.cn;
>   location /uptimerobot/ {
>     proxy_ssl_server_name on;
>     proxy_pass https://api.uptimerobot.com/;
>     proxy_hide_header Access-Control-Allow-Origin;
>     proxy_cache uptimerobot;
>     proxy_cache_methods POST;
>     add_header Access-Control-Allow-Origin * always;
>   }
>   location / {
>     return 301 https://status.org.cn;
>   }
> }
> ```

刚开始思路不对，只去看了官方状态页接口，后来想是不是有api提供，然后就代理了/v2目录的所有api，已经解决了
