### ISSUE TITLE
演示站无法打开

### ISSUE THREAD

**Issue by KS-OTO** [yb/uptime-status#57]
![image](https://github.com/user-attachments/assets/90b269b0-2682-4e11-8f0a-1b5b6fffc480)

**Comment by yb** [comment]
接口被刷了，触发了 UptimeRobot 限制

**Comment by KS-OTO** [comment]
https://help.18bit.cn/uptime/  目前我基于你项目做的状态监控站点，也经常如此，可否有优化方案呢？

**Comment by yb** [comment]
> https://help.18bit.cn/uptime/ 目前我基于你项目做的状态监控站点，也经常如此，可否有优化方案呢？

README 有自己部署反代接口的代码，可以试试，不一定有用，现在是 UptimeRobot 限制更严重了
