### ISSUE TITLE
要是能 自定义站点的 favicon.ico 那这个就可以做个友情的界面了.

### ISSUE THREAD

**Issue by ipme** [yb/uptime-status#6]
做一下 css 可以做个友情连接的单页了, 前端不用显示100% 这样的了,
只显示 红色,黄色 绿色,    红色表示 这个站点 404,或者在 站点在线率 太低了.
黄色,短暂不通...绿色正常,   

一般站点的友情连接,应该不会超过50个吧..  这个逻辑应该可以实现吧.

**Comment by yb** [comment]
favicon.ico 可以自己换嘛，准寻标准放在根目录下，实在想换地址就直接换 index.html 的代码嘛。
友情链接页面暂时不考虑，超出这个项目本身设计的目的了。
有啥建议随时欢迎提出~
