### ISSUE TITLE
今天发现的，不知道是哪的问题

### ISSUE THREAD

**Issue by haoziz** [yb/uptime-status#7]
![QQ截图20200319130205](https://user-images.githubusercontent.com/45513686/77033343-eb08c500-69e1-11ea-97a1-1e64468c7de7.jpg)

**Comment by yb** [comment]
可以附上 UptimeRobot 官网里的事件日志吗，或者如果你是 mjj 论坛来的，可以把 api key 私信给我看看。
因为 UptimeRobot 的事件日志不是按天来的，转换成每天的日志时，可能有疏漏，也没有太多样本可以考虑。

**Comment by haoziz** [comment]
ur836378-151af4c093930ea67f78a71c

**Comment by yb** [comment]
经过测试，是因为这个网站最近一次宕机发生在 2020-03-18 23:58:40 总共持续了 939 秒，持续到 2020-03-19 00:14:19 恢复。所以 03-19 的在线率没有100%，颜色也就变红了。而日志发生时间不在 03-19 所以 03-19 当天显示故障 0 次。

现阶段版本没有对事件日志的持续时间做跨天统计，也就导致了 “累计0秒” 的提示，后面会完善这个问题。

**Comment by haoziz** [comment]
ok，谢谢了
