### ISSUE TITLE
能不能把日期从左到右排？

### ISSUE THREAD

**Issue by xinxingli** [yb/uptime-status#9]
您好，我看到您做的这个页面特别漂亮，部署也非常的方便，但是我发现日期排列是从右到左排的，这于我们的习惯不符，您能不能改一下，感谢🙏

**Comment by yb** [comment]
从近到远，从左到右

**Comment by dayepao** [comment]
首先在uptimerobot.js 71 行后面加一行 daily.reverse();

然后修改下 uptime-item.js 的时间显示。
把第11行的
const initial = monitor.daily[monitor.daily.length - 1].date;
改为
const initial = monitor.daily[monitor.daily.length - 60].date;
然后交换第38行<span>今天</span>和第40行<span>{initial.format('YYYY-MM-DD')}</span>


如果下载的release版，则所有的js文件都集合在static\js\main.7d1555d4.js中，还是修改上面几处代码，但变量名称不同。

在var l = "unknow";后加入o.reverse();

把a = i.daily[i.daily.length - 1].date
改为a = i.daily[i.daily.length - 60].date

把o.a.createElement("span", null, "\u4eca\u5929"), o.a.createElement("span", null, u), o.a.createElement("span", null, a.format("YYYY-MM-DD"))
改为
o.a.createElement("span", null, a.format("YYYY-MM-DD")), o.a.createElement("span", null, u), o.a.createElement("span", null, "\u4eca\u5929")

**Comment by xinxingli** [comment]
> 首先在uptimerobot.js 71 行后面加一行 daily.reverse();
> 
> 然后修改下 uptime-item.js 的时间显示。
> 把第11行的
> const initial = monitor.daily[monitor.daily.length - 1].date;
> 改为
> const initial = monitor.daily[monitor.daily.length - 60].date;
> 然后交换第38行今天和第40行{initial.format('YYYY-MM-DD')}
> 
> 如果下载的release版，则所有的js文件都集合在static\js\main.7d1555d4.js中，还是修改上面几处代码，但变量名称不同。
> 
> 在var l = "unknow";后加入o.reverse();
> 
> 把a = i.daily[i.daily.length - 1].date
> 改为a = i.daily[i.daily.length - 60].date
> 
> 把o.a.createElement("span", null, "\u4eca\u5929"), o.a.createElement("span", null, u), o.a.createElement("span", null, a.format("YYYY-MM-DD"))
> 改为
> o.a.createElement("span", null, a.format("YYYY-MM-DD")), o.a.createElement("span", null, u), o.a.createElement("span", null, "\u4eca\u5929")

感谢大佬，成功了

**Comment by arturinious** [comment]
This not works in latest version.
